import Head from 'next/head'
import MediaCard from './components/MediaCard'
export default function Home() {
  return (
    <main>
      <Head>
        <title>Opskill Path</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        <h1>Opskill Path</h1>
        <p>open source path projects based on skill align with your goals or interests</p>
        <MediaCard/>
      </div>
   </main>
  )
}
